FROM python:3.7-slim
USER root
ENV LANG C.UTF-8
WORKDIR /PlantCV
EXPOSE 6005
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
#RUN apt-get update
COPY boto-hydrotek.txt /root/.boto
COPY hydrotek-serviceAcc.json /root
COPY . /PlantCV
RUN pip install -r requirements.txt
CMD ["python", "-u", "PlantCV_API_Final.py"]