apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pesttrainingautomation
  name: pesttrainingautomation
  namespace: dev
spec:
  selector:
    matchLabels:
      app: pesttrainingautomation
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pesttrainingautomation
    spec:
      containers:
      - image: gcr.io/hydrotek-286213/pesttrainingautomation:v1
        imagePullPolicy: IfNotPresent
        name: pesttrainingautomation
        resources:
          limits:
            cpu: 1250m
            ephemeral-storage: 8Gi
            memory: 8Gi
          requests:
            cpu: 1250m
            ephemeral-storage: 8Gi
            memory: 8Gi