apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fungaltrainingautomation
  name: fungaltrainingautomation
  namespace: dev
spec:
  selector:
    matchLabels:
      app: fungaltrainingautomation
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fungaltrainingautomation
    spec:
      containers:
      - image: gcr.io/hydrotek-286213/fungaltrainingautomation:v1
        imagePullPolicy: IfNotPresent
        name: fungaltrainingautomation
        resources:
          limits:
            cpu: 1250m
            ephemeral-storage: 8Gi
            memory: 8Gi
          requests:
            cpu: 1250m
            ephemeral-storage: 8Gi
            memory: 8Gi