# -*- coding: utf-8 -*-
"""DC_fastaiv2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10atRhe63liy8fHStbjhfrOQoAzX1posZ
"""

import warnings
warnings.filterwarnings("ignore")

pip install fastai --upgrade

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai import *
from fastai.vision.all import *
from fastai.metrics import error_rate, FBeta
from fastai.callback.core import *

data = ImageDataLoaders.from_folder(path='drive/My Drive/lettuce_new',
                                  item_tfms=RandomResizedCrop(256, min_scale=0.5), 
                                  train = 'lettuce_new', 
                                  valid_pct=0.15,
                                  batch_tfms=aug_transforms(),
                                  size =256,
                                  bs=10)

data.vocab

data.show_batch()

learn = cnn_learner(data,models.resnet50, loss_func=CrossEntropyLossFlat(), metrics= accuracy)

learn.save("model")

learn.fit_one_cycle(10, lr_max=slice(1e-4,1e-2), cbs=[SaveModelCallback(monitor="accuracy")])

interpret = ClassificationInterpretation.from_learner(learn)

interpret.plot_confusion_matrix(figsize=(10,10), dpi=60)

learn.export('/content/lettuce_new/')