apiVersion: v1
kind: Service
metadata:
  name: pestdetection-22-service
spec:
  selector:
    app: pestdetection-22
  ports:
  - protocol: "TCP"
    port: 5001
    targetPort: 5001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pestdetection-22
spec:
  selector:
    matchLabels:
      app: pestdetection-22
  replicas: 1
  template:
    metadata:
      labels:
        app: pestdetection-22
    spec:
      containers:
      - name: pestdetection-22
        image: pestdetection-22:v1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5001